!        Generated by TAPENADE     (INRIA, Tropics team)
!  Tapenade 3.9 (r5096) - 24 Feb 2014 16:54
!
!  Differentiation of soluterhs in forward (tangent) mode:
!   variations   of useful results: vbles soluterhs
!   with respect to varying inputs: vbles
!   RW status of diff variables: vbles:in-out soluterhs:out
DOUBLE PRECISION FUNCTION SOLUTERHS_D(vbles, vblesd, dx, c_dot, phi_dot&
& , c_c, soluterhs)
! this uses volume element method. This guarantees conservation of solute. The main source of solute is the variation of free ene
!rgy with phase: d (d F/dc) = ...+ (d^2 F/dc d phi) d phi + ..., which is revealed by a plot of c_dot.
  USE SOLUTION_PARAMETERS
  IMPLICIT NONE
  DOUBLE PRECISION, INTENT(IN) :: dx, c_dot, c_c, vbles(2, 3, 3)
  DOUBLE PRECISION, INTENT(IN) :: vblesd(2, 3, 3)
!integer, intent (in)::i,j,k,lb,df
  INTEGER :: ii, jj, ip, ih, jv
  DOUBLE PRECISION :: c, t, phi, FREEENERGY, d, phi_dot, phi_, phi_tmp
  DOUBLE PRECISION :: cd, td, phid, FREEENERGY_D, phi_dotd
  DOUBLE PRECISION, DIMENSION(3, 3), SAVE :: stencil11
  DOUBLE PRECISION, DIMENSION(3), SAVE :: stencil1=(/-.5, 0., .5/)
!double precision, dimension(3):: D1=(/6.7e-10,6.7e-12,6.7e-12/)!Jackson Hunt
  DOUBLE PRECISION, DIMENSION(3), SAVE :: d1=(/6.70e-10, 6.70e-12, &
&   6.70e-12/)
  DOUBLE PRECISION :: dfdc, potential, lap_c, d_, d_c, d_cc, d_c1, d_cc1&
& , grad_c(2), y0, g_phi, F_C, F_CC
  DOUBLE PRECISION :: d_cd, d_ccd, F_C_D, F_CC_D
! (m^2/s)    characteristic diffusivity delta2/tau=M*eps2(1)
  DOUBLE PRECISION, SAVE :: d_ch=2.83e-10
  DOUBLE PRECISION :: PHASERHS_C
  DOUBLE PRECISION :: PHASERHS_C_D
  DOUBLE PRECISION, SAVE :: beta=1d1
  INTRINSIC RESHAPE
  EXTERNAL F_C
  EXTERNAL F_C_D
  EXTERNAL F_CC
  EXTERNAL F_CC_D
  EXTERNAL FREEENERGY
  EXTERNAL FREEENERGY_D
  EXTERNAL PHASERHS_C
  EXTERNAL PHASERHS_C_D
  REAL, DIMENSION(9) :: arg1
  DOUBLE PRECISION :: result1
  DOUBLE PRECISION :: result1d
  DOUBLE PRECISION :: result2
  DOUBLE PRECISION :: result2d
  DOUBLE PRECISION :: soluterhs
  REAL :: delta
  DOUBLE PRECISION :: dxd
  DOUBLE PRECISION :: c_dotd
  arg1(:) = (/0., 6., 0., 6., -24., 6., 0., 6., 0./)
  stencil11 = RESHAPE(arg1(:), (/3, 3/))
! 
!changePCB
  beta = 0.0
!
  soluterhs = 0.
  d_ch = 2.83d-10
!
!if(df.eq.0)then
!x-coordinate transform values
!! Right
  ih = 3
  jv = 2
! The 0.34 = W/(R*T_melt*molpervol)=7e7/(8.31*456*54185)
  d = 0.
  d_c = 0.
  d_cc = 0.
!  D= 0.5 * D1(1)*( (1.+delta)*vbles(1,ih,jv)+(1.+delta)*vbles(1,2,2))
!  D_c=0.5* D1(1)*( vbles(1,ih,jv)*f_c(vbles(2,ih,jv),0) + vbles(1,2,2)*f_c(c_c,0))
!  D_cc= 0.5* D1(1)*( vbles(1,ih,jv)*f_cc(vbles(2,ih,jv),0) + vbles(1,2,2)*f_cc(c_c,0))
  d = d1(1)*(1.+delta)
  result1d = F_C_D(vbles(2, ih, jv), vblesd(2, ih, jv), 0, result1)
  result2 = F_C(c_c, 0)
  d_cd = 0.5*d1(1)*result1d
  d_c = 0.5*d1(1)*(result1+result2)
  result1d = F_CC_D(vbles(2, ih, jv), vblesd(2, ih, jv), 0, result1)
  result2 = F_CC(c_c, 0)
  d_ccd = 0.5*d1(1)*result1d
  d_cc = 0.5*d1(1)*(result1+result2)
  cd = vblesd(2, ih, jv)
  c = vbles(2, ih, jv)
  t = delta
  phid = vblesd(1, ih, jv)
  phi = vbles(1, ih, jv)
  phi_dotd = 0.D0
  c_dotd = 0.D0
  td = 0.D0
  result1d = FREEENERGY_D(c, cd, t, td, phi, phid, c_dot, c_dotd, &
&   phi_dot, phi_dotd, 2, result1)
  dxd = 0.D0
  result2d = PHASERHS_C_D(vbles, vblesd, dx, dxd, phi, phid, c, cd, t, &
&   td, c_dot, c_dotd, phi_dot, phi_dotd, result2)
  soluterhs_d = d_cd*(result1+beta*0.34*result2) + d_c*(result1d+beta*&
&   0.34*result2d) + d*cd + d_ccd*t + d_cc*td
  soluterhs = soluterhs + d_c*(result1+beta*0.34*result2) + d*c + d_cc*t
!  centre
  cd = vblesd(2, 2, 2)
  c = vbles(2, 2, 2)
  phid = vblesd(1, 2, 2)
  phi = vbles(1, 2, 2)
  result1d = FREEENERGY_D(c, cd, t, td, phi, phid, c_dot, c_dotd, &
&   phi_dot, phi_dotd, 2, result1)
  result2d = PHASERHS_C_D(vbles, vblesd, dx, dxd, phi, phid, c, cd, t, &
&   td, c_dot, c_dotd, phi_dot, phi_dotd, result2)
  soluterhs_d = soluterhs_d - d_cd*(result1+beta*0.34*result2) - d_c*(&
&   result1d+beta*0.34*result2d) - d*cd - d_ccd*t - d_cc*td
  soluterhs = soluterhs - d_c*(result1+beta*0.34*result2) - d*c - d_cc*t
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!Left !
  ih = 1
  jv = 2
! The 0.34 = W/(R*T_melt*molpervol)=7e7/(8.31*456*54185)
  d = 0.
  d_c = 0.
  d_cc = 0.
!  D= 0.5 * D1(1)*( (1.+delta)*vbles(1,ih,jv)+(1.+delta)*vbles(1,2,2))
!  D_c=0.5* D1(1)*( vbles(1,ih,jv)*f_c(vbles(2,ih,jv),0) + vbles(1,2,2)*f_c(c_c,0))
!  D_cc= 0.5* D1(1)*( vbles(1,ih,jv)*f_cc(vbles(2,ih,jv),0) + vbles(1,2,2)*f_cc(c_c,0))
  d = d1(1)*(1.+delta)
  result1d = F_C_D(vbles(2, ih, jv), vblesd(2, ih, jv), 0, result1)
  result2 = F_C(c_c, 0)
  d_cd = 0.5*d1(1)*result1d
  d_c = 0.5*d1(1)*(result1+result2)
  result1d = F_CC_D(vbles(2, ih, jv), vblesd(2, ih, jv), 0, result1)
  result2 = F_CC(c_c, 0)
  d_ccd = 0.5*d1(1)*result1d
  d_cc = 0.5*d1(1)*(result1+result2)
  cd = vblesd(2, ih, jv)
  c = vbles(2, ih, jv)
  t = delta
  phid = vblesd(1, ih, jv)
  phi = vbles(1, ih, jv)
  td = 0.D0
  result1d = FREEENERGY_D(c, cd, t, td, phi, phid, c_dot, c_dotd, &
&   phi_dot, phi_dotd, 2, result1)
  result2d = PHASERHS_C_D(vbles, vblesd, dx, dxd, phi, phid, c, cd, t, &
&   td, c_dot, c_dotd, phi_dot, phi_dotd, result2)
  soluterhs_d = soluterhs_d + d_cd*(result1+beta*0.34*result2) + d_c*(&
&   result1d+beta*0.34*result2d) + d*cd + d_ccd*t + d_cc*td
  soluterhs = soluterhs + d_c*(result1+beta*0.34*result2) + d*c + d_cc*t
!  centre
  cd = vblesd(2, 2, 2)
  c = vbles(2, 2, 2)
  phid = vblesd(1, 2, 2)
  phi = vbles(1, 2, 2)
  result1d = FREEENERGY_D(c, cd, t, td, phi, phid, c_dot, c_dotd, &
&   phi_dot, phi_dotd, 2, result1)
  result2d = PHASERHS_C_D(vbles, vblesd, dx, dxd, phi, phid, c, cd, t, &
&   td, c_dot, c_dotd, phi_dot, phi_dotd, result2)
  soluterhs_d = soluterhs_d - d_cd*(result1+beta*0.34*result2) - d_c*(&
&   result1d+beta*0.34*result2d) - d*cd - d_ccd*t - d_cc*td
  soluterhs = soluterhs - d_c*(result1+beta*0.34*result2) - d*c - d_cc*t
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!up
  ih = 2
  jv = 3
! The 0.34 = W/(R*T_melt*molpervol)=7e7/(8.31*456*54185)
  d = 0.
  d_c = 0.
  d_cc = 0.
!  D= 0.5 * D1(1)*( (1.+delta)*vbles(1,ih,jv)+(1.+delta)*vbles(1,2,2))
!  D_c=0.5* D1(1)*( vbles(1,ih,jv)*f_c(vbles(2,ih,jv),0) + vbles(1,2,2)*f_c(c_c,0))
!  D_cc= 0.5* D1(1)*( vbles(1,ih,jv)*f_cc(vbles(2,ih,jv),0) + vbles(1,2,2)*f_cc(c_c,0))
  d = d1(1)*(1.+delta)
  result1d = F_C_D(vbles(2, ih, jv), vblesd(2, ih, jv), 0, result1)
  result2 = F_C(c_c, 0)
  d_cd = 0.5*d1(1)*result1d
  d_c = 0.5*d1(1)*(result1+result2)
  result1d = F_CC_D(vbles(2, ih, jv), vblesd(2, ih, jv), 0, result1)
  result2 = F_CC(c_c, 0)
  d_ccd = 0.5*d1(1)*result1d
  d_cc = 0.5*d1(1)*(result1+result2)
  cd = vblesd(2, ih, jv)
  c = vbles(2, ih, jv)
  t = delta
  phid = vblesd(1, ih, jv)
  phi = vbles(1, ih, jv)
  td = 0.D0
  result1d = FREEENERGY_D(c, cd, t, td, phi, phid, c_dot, c_dotd, &
&   phi_dot, phi_dotd, 2, result1)
  result2d = PHASERHS_C_D(vbles, vblesd, dx, dxd, phi, phid, c, cd, t, &
&   td, c_dot, c_dotd, phi_dot, phi_dotd, result2)
  soluterhs_d = soluterhs_d + d_cd*(result1+beta*0.34*result2) + d_c*(&
&   result1d+beta*0.34*result2d) + d*cd + d_ccd*t + d_cc*td
  soluterhs = soluterhs + d_c*(result1+beta*0.34*result2) + d*c + d_cc*t
!  centre
  cd = vblesd(2, 2, 2)
  c = vbles(2, 2, 2)
  phid = vblesd(1, 2, 2)
  phi = vbles(1, 2, 2)
  result1d = FREEENERGY_D(c, cd, t, td, phi, phid, c_dot, c_dotd, &
&   phi_dot, phi_dotd, 2, result1)
  result2d = PHASERHS_C_D(vbles, vblesd, dx, dxd, phi, phid, c, cd, t, &
&   td, c_dot, c_dotd, phi_dot, phi_dotd, result2)
  soluterhs_d = soluterhs_d - d_cd*(result1+beta*0.34*result2) - d_c*(&
&   result1d+beta*0.34*result2d) - d*cd - d_ccd*t - d_cc*td
  soluterhs = soluterhs - d_c*(result1+beta*0.34*result2) - d*c - d_cc*t
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!down
  ih = 2
  jv = 1
! The 0.34 = W/(R*T_melt*molpervol)=7e7/(8.31*456*54185)
  d = 0.
  d_c = 0.
  d_cc = 0.
!  D= 0.5 * D1(1)*( (1.+delta)*vbles(1,ih,jv)+(1.+delta)*vbles(1,2,2))
!  D_c=0.5* D1(1)*( vbles(1,ih,jv)*f_c(vbles(2,ih,jv),0) + vbles(1,2,2)*f_c(c_c,0))
!  D_cc= 0.5* D1(1)*( vbles(1,ih,jv)*f_cc(vbles(2,ih,jv),0) + vbles(1,2,2)*f_cc(c_c,0))
  d = d1(1)*(1.+delta)
  result1d = F_C_D(vbles(2, ih, jv), vblesd(2, ih, jv), 0, result1)
  result2 = F_C(c_c, 0)
  d_cd = 0.5*d1(1)*result1d
  d_c = 0.5*d1(1)*(result1+result2)
  result1d = F_CC_D(vbles(2, ih, jv), vblesd(2, ih, jv), 0, result1)
  result2 = F_CC(c_c, 0)
  d_ccd = 0.5*d1(1)*result1d
  d_cc = 0.5*d1(1)*(result1+result2)
  cd = vblesd(2, ih, jv)
  c = vbles(2, ih, jv)
  t = delta
  phid = vblesd(1, ih, jv)
  phi = vbles(1, ih, jv)
  td = 0.D0
  result1d = FREEENERGY_D(c, cd, t, td, phi, phid, c_dot, c_dotd, &
&   phi_dot, phi_dotd, 2, result1)
  result2d = PHASERHS_C_D(vbles, vblesd, dx, dxd, phi, phid, c, cd, t, &
&   td, c_dot, c_dotd, phi_dot, phi_dotd, result2)
  soluterhs_d = soluterhs_d + d_cd*(result1+beta*0.34*result2) + d_c*(&
&   result1d+beta*0.34*result2d) + d*cd + d_ccd*t + d_cc*td
  soluterhs = soluterhs + d_c*(result1+beta*0.34*result2) + d*c + d_cc*t
!  centre
  cd = vblesd(2, 2, 2)
  c = vbles(2, 2, 2)
  phid = vblesd(1, 2, 2)
  phi = vbles(1, 2, 2)
  result1d = FREEENERGY_D(c, cd, t, td, phi, phid, c_dot, c_dotd, &
&   phi_dot, phi_dotd, 2, result1)
  result2d = PHASERHS_C_D(vbles, vblesd, dx, dxd, phi, phid, c, cd, t, &
&   td, c_dot, c_dotd, phi_dot, phi_dotd, result2)
  soluterhs_d = soluterhs_d - d_cd*(result1+beta*0.34*result2) - d_c*(&
&   result1d+beta*0.34*result2d) - d*cd - d_ccd*t - d_cc*td
  soluterhs = soluterhs - d_c*(result1+beta*0.34*result2) - d*c - d_cc*t
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  soluterhs_d = (soluterhs_d*dx**2/d_ch-soluterhs*(dxd*dx+dx*dxd)/d_ch)/&
&   (dx*dx)**2
  soluterhs = soluterhs/d_ch/(dx*dx)
! SoluteRHS = SoluteRHS+v_mesh*(unk(1+4*nunkvbles,i+1,j,k,lb)-unk(1+4*nunkvbles,i,j,k,lb))/(dx)
!  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  RETURN
END FUNCTION SOLUTERHS_D
